#!/usr/bin/env python3
"""GCL Phase 4 — plan Huawei Cloud CES alarms for GCL quality SLOs.

Consumes a `gcl-quality-summary-*.json` generated by `gcl_trace_aggregate.py` and
renders the CES custom-metric alarm plan. `plan` is read-only; `apply --dry-run`
prints the same mutation plan. Non-dry-run `apply` shells out to `hcloud ces` and
must only be used with explicit operator approval.

Usage:
  python3 scripts/gcl_alarm_wire.py plan --summary audit-results/gcl-quality-summary-LATEST.json
  python3 scripts/gcl_alarm_wire.py apply --summary audit-results/gcl-quality-summary-LATEST.json --dry-run
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_THRESHOLDS = {
    "pass_rate_warn": 0.85,
    "pass_rate_critical": 0.70,
    "max_iter_warn_count": 3,
    "safety_fail_alert": True,
}

GCL_NAMESPACE = "CUSTOM.GCL"
GCL_PASS_RATE_METRIC = "gcl_overall_pass_rate"
GCL_SAFETY_FAIL_METRIC = "gcl_safety_fail_count"
GCL_MAX_ITER_METRIC = "gcl_max_iter_count"

PLAN_GLOB = "audit-results/gcl-alarm-plan-*.json"


def load_latest_summary(audit_dir: Path) -> Path | None:
    paths = sorted(audit_dir.glob("gcl-quality-summary-*.json"))
    return paths[-1] if paths else None


def parse_summary(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_thresholds_from_config(config_path: Path) -> dict[str, Any]:
    thresholds: dict[str, Any] = dict(DEFAULT_THRESHOLDS)
    if not config_path.exists():
        return thresholds
    in_block = False
    for line in config_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("gcl_quality:"):
            in_block = True
            continue
        if in_block:
            if not line.startswith(" ") and ":" in stripped:
                break
            if ":" not in stripped:
                continue
            key, _, raw = stripped.partition(":")
            key = key.strip()
            raw = raw.strip().split("#")[0].strip()
            if key not in DEFAULT_THRESHOLDS:
                continue
            if raw.lower() in ("true", "false"):
                thresholds[key] = raw.lower() == "true"
            else:
                try:
                    thresholds[key] = float(raw)
                except ValueError:
                    pass
    return thresholds


def evaluate(summary: dict[str, Any], thresholds: dict[str, Any]) -> dict[str, Any]:
    totals = summary.get("totals", {}) or {}
    pass_rate = float(summary.get("pass_rate", 0.0))
    safety_fail = int(totals.get("SAFETY_FAIL", 0))
    max_iter = int(totals.get("MAX_ITER", 0))

    breaches: list[dict[str, str]] = []
    if pass_rate < float(thresholds["pass_rate_critical"]):
        breaches.append({
            "severity": "CRITICAL",
            "metric": "pass_rate",
            "value": str(pass_rate),
            "threshold": f"< {thresholds['pass_rate_critical']}",
            "message": f"GCL pass_rate {pass_rate} below critical {thresholds['pass_rate_critical']}",
        })
    elif pass_rate < float(thresholds["pass_rate_warn"]):
        breaches.append({
            "severity": "WARN",
            "metric": "pass_rate",
            "value": str(pass_rate),
            "threshold": f"< {thresholds['pass_rate_warn']}",
            "message": f"GCL pass_rate {pass_rate} below warn {thresholds['pass_rate_warn']}",
        })

    if bool(thresholds["safety_fail_alert"]) and safety_fail > 0:
        breaches.append({
            "severity": "CRITICAL",
            "metric": "safety_fail_count",
            "value": str(safety_fail),
            "threshold": "== 0",
            "message": f"GCL observed {safety_fail} SAFETY_FAIL trace(s)",
        })

    if max_iter > int(thresholds["max_iter_warn_count"]):
        breaches.append({
            "severity": "WARN",
            "metric": "max_iter_count",
            "value": str(max_iter),
            "threshold": f"<= {thresholds['max_iter_warn_count']}",
            "message": f"GCL hit MAX_ITER {max_iter} time(s)",
        })

    return {
        "pass_rate": pass_rate,
        "safety_fail": safety_fail,
        "max_iter": max_iter,
        "breaches": breaches,
        "ok": not any(breach["severity"] == "CRITICAL" for breach in breaches),
    }


def render_plan(evaluation: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {
            "op": "create-or-update-alarm-rule",
            "name": "gcl-overall-pass-rate-critical",
            "namespace": GCL_NAMESPACE,
            "metric_name": GCL_PASS_RATE_METRIC,
            "comparison_operator": "LT",
            "threshold": evaluation.get("_pass_rate_critical", 0.70),
            "period": 300,
            "evaluation_periods": 3,
            "severity": "CRITICAL",
            "description": "Fires when GCL pass_rate is below critical threshold.",
        },
        {
            "op": "create-or-update-alarm-rule",
            "name": "gcl-overall-pass-rate-warn",
            "namespace": GCL_NAMESPACE,
            "metric_name": GCL_PASS_RATE_METRIC,
            "comparison_operator": "LT",
            "threshold": evaluation.get("_pass_rate_warn", 0.85),
            "period": 300,
            "evaluation_periods": 3,
            "severity": "WARN",
            "description": "Fires when GCL pass_rate is below warning threshold.",
        },
        {
            "op": "create-or-update-alarm-rule",
            "name": "gcl-safety-fail-critical",
            "namespace": GCL_NAMESPACE,
            "metric_name": GCL_SAFETY_FAIL_METRIC,
            "comparison_operator": "GT",
            "threshold": 0,
            "period": 60,
            "evaluation_periods": 1,
            "severity": "CRITICAL",
            "description": "Fires on any GCL SAFETY_FAIL.",
        },
        {
            "op": "create-or-update-alarm-rule",
            "name": "gcl-max-iter-warning",
            "namespace": GCL_NAMESPACE,
            "metric_name": GCL_MAX_ITER_METRIC,
            "comparison_operator": "GT",
            "threshold": evaluation.get("_max_iter_warn_count", 3),
            "period": 300,
            "evaluation_periods": 2,
            "severity": "WARN",
            "description": "Fires when GCL MAX_ITER count exceeds threshold.",
        },
    ]


def build_report(args: argparse.Namespace) -> tuple[dict[str, Any], dict[str, Any]] | None:
    summary_path = args.summary
    if not summary_path:
        summary_path = load_latest_summary(args.root / "audit-results")
        if not summary_path:
            print("ERROR: No gcl-quality-summary-*.json found under audit-results/", file=sys.stderr)
            return None
    summary = parse_summary(summary_path)
    thresholds = load_thresholds_from_config(args.config)
    evaluation = evaluate(summary, thresholds)
    evaluation["_pass_rate_warn"] = thresholds["pass_rate_warn"]
    evaluation["_pass_rate_critical"] = thresholds["pass_rate_critical"]
    evaluation["_max_iter_warn_count"] = thresholds["max_iter_warn_count"]
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "cloud": "huaweicloud",
        "metric_namespace": GCL_NAMESPACE,
        "summary_path": str(summary_path),
        "thresholds": thresholds,
        "evaluation": {key: value for key, value in evaluation.items() if not key.startswith("_")},
        "alarm_plan": render_plan(evaluation),
    }
    return report, evaluation


def write_plan(root: Path, report: dict[str, Any], suffix: str) -> Path:
    audit_dir = root / "audit-results"
    audit_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    path = audit_dir / f"gcl-alarm-plan-{stamp}-{suffix}.json"
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def cmd_plan(args: argparse.Namespace) -> int:
    built = build_report(args)
    if built is None:
        return 2
    report, evaluation = built
    print(json.dumps(report, indent=2, ensure_ascii=False))
    if getattr(args, "write_plan", False):
        path = write_plan(args.root, report, suffix="plan")
        print(f"[plan] wrote {path}", file=sys.stderr)
    if not evaluation["ok"]:
        print(f"SLO breach detected — {len(evaluation['breaches'])} item(s).", file=sys.stderr)
        return 1
    return 0


def cmd_apply(args: argparse.Namespace) -> int:
    built = build_report(args)
    if built is None:
        return 2
    report, _evaluation = built
    plan = report["alarm_plan"]
    if args.dry_run:
        report = {**report, "dry_run": True}
        path = write_plan(args.root, report, suffix="dry-run")
        print(json.dumps(report, indent=2, ensure_ascii=False))
        print(f"[apply] dry-run wrote {path}", file=sys.stderr)
        return 0

    rc = 0
    for entry in plan:
        cmd = [
            "hcloud",
            "ces",
            "create-alarm-rule",
            "--name",
            entry["name"],
            "--namespace",
            entry["namespace"],
            "--metric-name",
            entry["metric_name"],
            "--comparison-operator",
            entry["comparison_operator"],
            "--threshold",
            str(entry["threshold"]),
            "--period",
            str(entry["period"]),
            "--evaluation-periods",
            str(entry["evaluation_periods"]),
        ]
        print(f"[apply] {' '.join(shlex.quote(part) for part in cmd)}")
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except subprocess.TimeoutExpired:
            print(f"[apply] TIMEOUT on {entry['name']}", file=sys.stderr)
            rc = 3
            continue
        if proc.returncode != 0:
            print(f"[apply] FAILED ({proc.returncode}): {proc.stderr or proc.stdout}", file=sys.stderr)
            rc = 3
            continue
        print(f"[apply] OK: {entry['name']}")
    return rc


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    subparsers = parser.add_subparsers(dest="cmd", required=True)

    plan = subparsers.add_parser("plan", help="Evaluate summary, render CES alarm plan")
    plan.add_argument("--config", type=Path, default=Path("huaweicloud-ces-ops/assets/example-config.yaml"))
    plan.add_argument("--summary", type=Path, default=None)
    plan.add_argument("--write-plan", action="store_true", help="Persist the plan JSON to audit-results/ for CI validation")
    plan.set_defaults(func=cmd_plan)

    apply = subparsers.add_parser("apply", help="Apply CES alarm plan via hcloud")
    apply.add_argument("--config", type=Path, default=Path("huaweicloud-ces-ops/assets/example-config.yaml"))
    apply.add_argument("--summary", type=Path, default=None)
    apply.add_argument("--dry-run", action="store_true")
    apply.set_defaults(func=cmd_apply)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
