"""Generate failure_patterns.json + remediation-playbooks.json for RDS/VPC/ELB/CCE.

Run once to bootstrap the knowledge base for the Top-5 high-frequency skills (ECS already exists).
Schema mirrors huaweicloud-ecs-ops/assets/{failure_patterns,remediation-playbooks}.json.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

UTC = timezone.utc  # noqa: UP017
NOW = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

ROOT = Path(__file__).resolve().parents[1]

# ---------------------------------------------------------------------------
# Knowledge base templates per product
# ---------------------------------------------------------------------------

PRODUCTS: dict[str, dict[str, list[dict]]] = {
    "rds": {
        "patterns": [
            {"id": "RDS-FP001", "category": "resource_state", "signature": {"error_code": "DBS.200001", "error_message_regex": "instance.*not found|InstanceNotFound", "command_pattern": "describe-instance"}, "root_cause": "DB instance ID invalid or instance deleted", "fix": {"strategy": "retry", "action": "List instances to verify ID: hcloud RDS listInstances --region {{env.HW_REGION_ID}} --limit 50"}, "prevention": "Cache instance ID from listInstances before state operations"},
            {"id": "RDS-FP002", "category": "resource_state", "signature": {"error_code": "DBS.200013", "error_message_regex": "instance.*not.*running|InvalidDBInstanceState", "command_pattern": "*"}, "root_cause": "Operation attempted while DB in transitional state (Creating/Restarting/FlavorChanging)", "fix": {"strategy": "retry", "action": "Poll showInstance until status==ACTIVE, then retry"}, "prevention": "Pre-check status before state-mutating operations"},
            {"id": "RDS-FP003", "category": "permission", "signature": {"error_code": "DBS.200028", "error_message_regex": "Quota exceeded|InstanceQuota", "command_pattern": "create-instance"}, "root_cause": "RDS instance quota exhausted for project/region", "fix": {"strategy": "halt", "action": "Delegate to huaweicloud-iam-ops for quota raise; do not retry"}, "prevention": "Check RDS quota via listQuotas before batch create"},
            {"id": "RDS-FP004", "category": "cross_skill", "signature": {"error_code": "DBS.201011", "error_message_regex": "VPC.*not found|subnet.*not found", "command_pattern": "create-instance"}, "root_cause": "VPC/subnet does not exist or wrong region", "fix": {"strategy": "delegate", "action": "Delegate to huaweicloud-vpc-ops to verify/create VPC+subnet, then retry RDS create"}, "prevention": "Verify vpc_id/subnet_id + cross-region match before create"},
            {"id": "RDS-FP005", "category": "network", "signature": {"error_code": "DBS.201015", "error_message_regex": "connection.*timeout|connect.*refused", "command_pattern": "*"}, "root_cause": "Network ACL/security group blocks 3306/5432/1433 traffic to RDS", "fix": {"strategy": "fallback", "action": "Inspect security group: hcloud VPC showSecurityGroup --id {{output.sg_id}}; ensure inbound allows client CIDR on DB port"}, "prevention": "Validate SG rules + NACL at provisioning time"},
            {"id": "RDS-FP006", "category": "runtime", "signature": {"error_code": "", "error_message_regex": "RequestLimitExceeded|Throttling", "command_pattern": "*"}, "root_cause": "API rate limit exceeded during burst operations", "fix": {"strategy": "retry", "action": "Exponential backoff: 2^n seconds (cap 60s), respect Retry-After header"}, "prevention": "Throttle batch operations; respect per-API rate limits"},
            {"id": "RDS-FP007", "category": "resource_state", "signature": {"error_code": "DBS.200301", "error_message_regex": "storage.*full|diskfull", "command_pattern": "*"}, "root_cause": "Disk space exhausted; writes failing", "fix": {"strategy": "fallback", "action": "Extend volume: hcloud RDS enlargeInstanceVolume --instance_id {{output.id}} --size {{output.new_size}}; or prune old backups"}, "prevention": "Monitor disk_util via CES; alarm at 80%"},
            {"id": "RDS-FP008", "category": "cli_parameter", "signature": {"error_code": "DBS.200021", "error_message_regex": "InvalidParameter|flavor.*invalid", "command_pattern": "create-instance"}, "root_cause": "flavor_ref / engine_version / HA mode invalid", "fix": {"strategy": "retry", "action": "List valid flavors: hcloud RDS listFlavors --region {{env.HW_REGION_ID}} --engine_type {{output.engine}}"}, "prevention": "Validate flavor via listFlavors before create"},
            {"id": "RDS-FP009", "category": "cli_parameter", "signature": {"error_code": "DBS.200019", "error_message_regex": "password.*policy|weak.*password", "command_pattern": "create-instance"}, "root_cause": "DB root password violates complexity policy", "fix": {"strategy": "retry", "action": "Use a password meeting: 8-32 chars, 3 of {upper,lower,digit,special}; do NOT log the password"}, "prevention": "Generate password client-side with policy validator"},
            {"id": "RDS-FP010", "category": "runtime", "signature": {"error_code": "DBS.202005", "error_message_regex": "backup.*failed|BackupError", "command_pattern": "create-backup"}, "root_cause": "Backup window collision or storage backend unavailable", "fix": {"strategy": "fallback", "action": "Retry with --wait_until off-peak or delegate to huaweicloud-cbr-ops for cross-region backup"}, "prevention": "Schedule backups in low-traffic windows; verify CBR policy"},
        ],
        "playbooks": [
            {"id": "RDS-R001", "name": "DB CPU High Restart Process", "trigger": {"metric": "rds_cpu_util", "condition": "> 90 for 5min", "namespace": "SYS.RDS"}, "diagnosis": {"steps": ["hcloud CES getMetricData --namespace SYS.RDS --metric_name cpu_util --period 60 --filter avg --dim instance_id={{output.instance_id}}", "hcloud RDS listSlowLogs --instance_id {{output.instance_id}} --top 20"], "confidence_factors": ["cpu_sustained_high", "slow_queries_present", "no_long_running_txn"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.85, "preconditions": ["hcloud RDS showInstance --instance_id {{output.instance_id}} | grep -q ACTIVE"], "dry_run": "hcloud RDS restartInstance --instance_id {{output.instance_id}} --dry-run", "execute": "hcloud RDS restartInstance --instance_id {{output.instance_id}}", "verification": "hcloud CES getMetricData --namespace SYS.RDS --metric_name cpu_util --period 60 --filter avg --dim instance_id={{output.instance_id}} | python3 -c \"import sys,json; d=json.load(sys.stdin); sys.exit(0 if d[-1]['average']<90 else 1)\"", "rollback": None, "timeout_seconds": 180}, "escalation": {"condition": "restart fails twice or instance in HA failover", "channel": "notification"}, "metadata": {"success_rate": 0.95, "avg_execution_seconds": 120, "last_updated": NOW, "learned_from": []}},
            {"id": "RDS-R002", "name": "Disk Space Low Volume Expand", "trigger": {"metric": "rds_disk_util", "condition": "> 85 for 5min", "namespace": "SYS.RDS"}, "diagnosis": {"steps": ["hcloud RDS showInstance --instance_id {{output.instance_id}}", "hcloud CES getMetricData --namespace SYS.RDS --metric_name disk_util --period 300 --filter avg --dim instance_id={{output.instance_id}}"], "confidence_factors": ["disk_growing", "no_recent_expand", "quota_available"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.9, "preconditions": ["hcloud RDS showInstanceVolume --instance_id {{output.instance_id}} | grep -q available"], "dry_run": "hcloud RDS enlargeInstanceVolume --instance_id {{output.instance_id}} --size {{output.new_size}} --dry-run", "execute": "hcloud RDS enlargeInstanceVolume --instance_id {{output.instance_id}} --size {{output.new_size}}", "verification": "hcloud RDS showInstanceVolume --instance_id {{output.instance_id}} | grep -q {{output.new_size}}", "rollback": None, "timeout_seconds": 600}, "escalation": {"condition": "expand fails or storage type does not support online expand", "channel": "notification"}, "metadata": {"success_rate": 0.98, "avg_execution_seconds": 300, "last_updated": NOW, "learned_from": []}},
            {"id": "RDS-R003", "name": "Connection Count High Failover", "trigger": {"metric": "rds_connections", "condition": "> 90% of max_connections", "namespace": "SYS.RDS"}, "diagnosis": {"steps": ["hcloud CES getMetricData --namespace SYS.RDS --metric_name connections --period 60 --filter avg --dim instance_id={{output.instance_id}}", "hcloud RDS listSessions --instance_id {{output.instance_id}} --limit 50"], "confidence_factors": ["connections_saturated", "long_idle_sessions", "pool_misconfigured"]}, "remediation": {"risk_level": "low", "auto_execute_threshold": 0.8, "preconditions": ["hcloud RDS showInstance --instance_id {{output.instance_id}} | grep -q ACTIVE"], "dry_run": "hcloud RDS killSessions --instance_id {{output.instance_id}} --session_ids {{output.idle_session_ids}} --dry-run", "execute": "hcloud RDS killSessions --instance_id {{output.instance_id}} --session_ids {{output.idle_session_ids}}", "verification": "hcloud CES getMetricData --namespace SYS.RDS --metric_name connections --period 60 --filter avg --dim instance_id={{output.instance_id}} | python3 -c \"import sys,json; d=json.load(sys.stdin); sys.exit(0 if d[-1]['average']<80 else 1)\"", "rollback": None, "timeout_seconds": 60}, "escalation": {"condition": "kill sessions insufficient or instance needs restart", "channel": "notification"}, "metadata": {"success_rate": 0.94, "avg_execution_seconds": 30, "last_updated": NOW, "learned_from": []}},
            {"id": "RDS-R004", "name": "Primary Failover Promote Standby", "trigger": {"metric": "rds_ha_role", "condition": "primary unreachable for 60s, standby healthy", "namespace": "SYS.RDS"}, "diagnosis": {"steps": ["hcloud RDS listInstances --status ACTIVE --ha_mode HA --limit 50", "hcloud CES getMetricData --namespace SYS.RDS --metric_name ha_role --period 30 --filter avg"], "confidence_factors": ["primary_down_confirmed", "standby_healthy", "network_partition_or_hw_failure"]}, "remediation": {"risk_level": "high", "auto_execute_threshold": 0.95, "preconditions": ["hcloud RDS showInstance --instance_id {{output.standby_id}} | grep -q ACTIVE", "hcloud RDS showInstance --instance_id {{output.primary_id}} | grep -qE 'FAILED|ERROR'"], "dry_run": "hcloud RDS failoverInstance --instance_id {{output.primary_id}} --dry-run", "execute": "hcloud RDS failoverInstance --instance_id {{output.primary_id}}", "verification": "hcloud CES getMetricData --namespace SYS.RDS --metric_name ha_role --period 30 --filter avg --dim instance_id={{output.standby_id}} | grep -q primary", "rollback": None, "timeout_seconds": 300}, "escalation": {"condition": "both nodes unhealthy or data divergence detected", "channel": "notification+pagerduty"}, "metadata": {"success_rate": 0.97, "avg_execution_seconds": 90, "last_updated": NOW, "learned_from": []}},
        ],
    },
    "vpc": {
        "patterns": [
            {"id": "VPC-FP001", "category": "resource_state", "signature": {"error_code": "VPC.0001", "error_message_regex": "VPC.*not found|VpcNotFound", "command_pattern": "*"}, "root_cause": "VPC ID invalid or VPC deleted", "fix": {"strategy": "retry", "action": "List VPCs: hcloud VPC listVpcs --region {{env.HW_REGION_ID}}"}, "prevention": "Cache VPC ID from listVpcs before operations"},
            {"id": "VPC-FP002", "category": "cli_parameter", "signature": {"error_code": "VPC.0007", "error_message_regex": "CIDR.*conflict|CidrConflict", "command_pattern": "create-subnet"}, "root_cause": "Subnet CIDR overlaps existing subnet in same VPC", "fix": {"strategy": "retry", "action": "List existing subnets: hcloud VPC listSubnets --vpc_id {{output.vpc_id}}; pick a non-overlapping /24"}, "prevention": "Pre-allocate non-overlapping CIDR plan; validate before create"},
            {"id": "VPC-FP003", "category": "resource_state", "signature": {"error_code": "VPC.0501", "error_message_regex": "security.*group.*not.*found|SgNotFound", "command_pattern": "*"}, "root_cause": "Security group ID invalid or already deleted", "fix": {"strategy": "retry", "action": "hcloud VPC listSecurityGroups --vpc_id {{output.vpc_id}}"}, "prevention": "Cache SG ID at provisioning time"},
            {"id": "VPC-FP004", "category": "permission", "signature": {"error_code": "VPC.0601", "error_message_regex": "Quota exceeded|ResourceQuota", "command_pattern": "*"}, "root_cause": "VPC/subnet/EIP quota exhausted", "fix": {"strategy": "halt", "action": "Delegate to huaweicloud-iam-ops for quota raise"}, "prevention": "Check quota via showQuota before bulk operations"},
            {"id": "VPC-FP005", "category": "cli_parameter", "signature": {"error_code": "VPC.0010", "error_message_regex": "rule.*conflict|RuleConflict", "command_pattern": "create-security-group-rule"}, "root_cause": "Duplicate/conflicting SG rule (same direction+port+remote) exists", "fix": {"strategy": "retry", "action": "List existing rules: hcloud VPC showSecurityGroup --id {{output.sg_id}}; dedupe"}, "prevention": "Diff existing rules before add; idempotent apply"},
            {"id": "VPC-FP006", "category": "runtime", "signature": {"error_code": "", "error_message_regex": "RequestLimitExceeded|Throttling", "command_pattern": "*"}, "root_cause": "API rate limit on VPC control plane", "fix": {"strategy": "retry", "action": "Exponential backoff with jitter; respect Retry-After"}, "prevention": "Throttle batch operations to <5 req/s"},
            {"id": "VPC-FP007", "category": "network", "signature": {"error_code": "VPC.0700", "error_message_regex": "EIP.*bind.*failed|elastic.*ip.*in.*use", "command_pattern": "associate-eip"}, "root_cause": "EIP already bound to another resource", "fix": {"strategy": "fallback", "action": "Unbind first: hcloud VPC disassociateEip --eip_id {{output.eip_id}}; or pick another EIP"}, "prevention": "Track EIP-resource binding via CTS before reuse"},
            {"id": "VPC-FP008", "category": "cli_parameter", "signature": {"error_code": "VPC.0011", "error_message_regex": "peering.*not.*found|PeeringNotFound", "command_pattern": "*"}, "root_cause": "VPC peering ID invalid or rejected by remote VPC", "fix": {"strategy": "retry", "action": "Verify acceptance: hcloud VPC listVpcPeerings --status PENDING_ACCEPTANCE; ensure both VPCs in same project"}, "prevention": "Validate peering config + acceptance state before traffic"},
            {"id": "VPC-FP009", "category": "cross_skill", "signature": {"error_code": "VPC.0012", "error_message_regex": "route.*table.*conflict|RouteTableConflict", "command_pattern": "*"}, "root_cause": "Default route table + custom route table both applied to same subnet", "fix": {"strategy": "fallback", "action": "Disassociate custom route table: hcloud VPC disassociateRouteTable --subnet_id {{output.subnet_id}}"}, "prevention": "Use custom route tables only; document subnet associations"},
            {"id": "VPC-FP010", "category": "network", "signature": {"error_code": "VPC.0701", "error_message_regex": "bandwidth.*insufficient|BandwidthExceeded", "command_pattern": "*"}, "root_cause": "EIP bandwidth cap reached; throttle or upgrade", "fix": {"strategy": "fallback", "action": "Modify EIP bandwidth: hcloud VPC updateEipBandwidth --eip_id {{output.eip_id}} --bandwidth {{output.bw_mbps}}"}, "prevention": "Monitor CES metric `eip_bandwidth_util`; alarm at 80%"},
        ],
        "playbooks": [
            {"id": "VPC-R001", "name": "Security Group Rule Stale Cleanup", "trigger": {"metric": "sg_unused_rules", "condition": "> 5 rules unused for 30d", "namespace": "SYS.VPC"}, "diagnosis": {"steps": ["hcloud VPC showSecurityGroup --id {{output.sg_id}}", "hcloud CTS listTraces --resource_type security_group --limit 100"], "confidence_factors": ["rules_unused", "no_recent_match", "no_compliance_lock"]}, "remediation": {"risk_level": "low", "auto_execute_threshold": 0.85, "preconditions": ["hcloud VPC showSecurityGroup --id {{output.sg_id}} | grep -q active"], "dry_run": "hcloud VPC deleteSecurityGroupRule --sg_id {{output.sg_id}} --rule_id {{output.rule_id}} --dry-run", "execute": "hcloud VPC deleteSecurityGroupRule --sg_id {{output.sg_id}} --rule_id {{output.rule_id}}", "verification": "hcloud VPC showSecurityGroup --id {{output.sg_id}} | grep -q {{output.rule_id}} || true", "rollback": "hcloud VPC createSecurityGroupRule --sg_id {{output.sg_id}} --rule {{output.rule_payload}}", "timeout_seconds": 30}, "escalation": {"condition": "rule still referenced by another SG or compliance flag set", "channel": "notification"}, "metadata": {"success_rate": 0.99, "avg_execution_seconds": 10, "last_updated": NOW, "learned_from": []}},
            {"id": "VPC-R002", "name": "Subnet CIDR Auto-Allocate", "trigger": {"metric": "subnet_available_ips", "condition": "< 10 remaining", "namespace": "SYS.VPC"}, "diagnosis": {"steps": ["hcloud VPC showSubnet --subnet_id {{output.subnet_id}}", "hcloud VPC listSubnets --vpc_id {{output.vpc_id}}"], "confidence_factors": ["cidr_exhausted", "vpc_cidr_room_available", "no_overlap"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.9, "preconditions": ["hcloud VPC listVpcs --vpc_id {{output.vpc_id}} | grep -q ACTIVE"], "dry_run": "hcloud VPC createSubnet --vpc_id {{output.vpc_id}} --cidr {{output.next_cidr}} --dry-run", "execute": "hcloud VPC createSubnet --vpc_id {{output.vpc_id}} --cidr {{output.next_cidr}}", "verification": "hcloud VPC showSubnet --subnet_id {{output.new_subnet_id}} | grep -q ACTIVE", "rollback": "hcloud VPC deleteSubnet --subnet_id {{output.new_subnet_id}}", "timeout_seconds": 60}, "escalation": {"condition": "VPC CIDR fully consumed; needs new VPC", "channel": "notification+pagerduty"}, "metadata": {"success_rate": 0.96, "avg_execution_seconds": 30, "last_updated": NOW, "learned_from": []}},
            {"id": "VPC-R003", "name": "EIP Bandwidth Upgrade", "trigger": {"metric": "eip_bandwidth_util", "condition": "> 85 for 5min", "namespace": "SYS.VPC"}, "diagnosis": {"steps": ["hcloud CES getMetricData --namespace SYS.VPC --metric_name eip_bandwidth_util --period 60 --filter avg", "hcloud VPC showEip --eip_id {{output.eip_id}}"], "confidence_factors": ["bw_sustained_high", "quota_available", "no_maintenance_window"]}, "remediation": {"risk_level": "low", "auto_execute_threshold": 0.9, "preconditions": ["hcloud VPC showEip --eip_id {{output.eip_id}} | grep -q ACTIVE"], "dry_run": "hcloud VPC updateEipBandwidth --eip_id {{output.eip_id}} --bandwidth {{output.bw_mbps}} --dry-run", "execute": "hcloud VPC updateEipBandwidth --eip_id {{output.eip_id}} --bandwidth {{output.bw_mbps}}", "verification": "hcloud VPC showEip --eip_id {{output.eip_id}} | grep -q {{output.bw_mbps}}", "rollback": "hcloud VPC updateEipBandwidth --eip_id {{output.eip_id}} --bandwidth {{output.old_bw}}", "timeout_seconds": 30}, "escalation": {"condition": "bandwidth upgrade fails or quota exhausted", "channel": "notification"}, "metadata": {"success_rate": 0.99, "avg_execution_seconds": 10, "last_updated": NOW, "learned_from": []}},
            {"id": "VPC-R004", "name": "ACL Route Drift Repair", "trigger": {"metric": "route_drift_count", "condition": "> 0 missing routes for 5min", "namespace": "SYS.VPC"}, "diagnosis": {"steps": ["hcloud VPC showRouteTable --route_table_id {{output.rt_id}}", "hcloud VPC listVpcPeerings --status ACTIVE"], "confidence_factors": ["routes_missing", "peering_active", "config_known"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.9, "preconditions": ["hcloud VPC showRouteTable --route_table_id {{output.rt_id}} | grep -q ACTIVE"], "dry_run": "hcloud VPC createRoutes --route_table_id {{output.rt_id}} --routes {{output.routes_json}} --dry-run", "execute": "hcloud VPC createRoutes --route_table_id {{output.rt_id}} --routes {{output.routes_json}}", "verification": "hcloud VPC showRouteTable --route_table_id {{output.rt_id}} | grep -q {{output.expected_destination_cidr}}", "rollback": "hcloud VPC deleteRoutes --route_table_id {{output.rt_id}} --routes {{output.routes_json}}", "timeout_seconds": 30}, "escalation": {"condition": "routes still missing after apply", "channel": "notification"}, "metadata": {"success_rate": 0.97, "avg_execution_seconds": 15, "last_updated": NOW, "learned_from": []}},
        ],
    },
    "elb": {
        "patterns": [
            {"id": "ELB-FP001", "category": "resource_state", "signature": {"error_code": "ELB.0001", "error_message_regex": "loadbalancer.*not found|LbNotFound", "command_pattern": "*"}, "root_cause": "LB ID invalid or LB deleted", "fix": {"strategy": "retry", "action": "hcloud ELB listLoadBalancers --region {{env.HW_REGION_ID}}"}, "prevention": "Cache LB ID at provisioning time"},
            {"id": "ELB-FP002", "category": "resource_state", "signature": {"error_code": "ELB.0104", "error_message_regex": "backend.*unhealthy|HealthCheckFailed", "command_pattern": "*"}, "root_cause": "Backend instance health check failing: port blocked, app down, or SG mismatch", "fix": {"strategy": "fallback", "action": "Inspect backend: hcloud ELB listMembers --lb_id {{output.lb_id}}; check SG allows LB->backend traffic on health-check port"}, "prevention": "Validate SG rules + health-check port at LB add time"},
            {"id": "ELB-FP003", "category": "cli_parameter", "signature": {"error_code": "ELB.0201", "error_message_regex": "listener.*port.*conflict|PortConflict", "command_pattern": "create-listener"}, "root_cause": "Port already used by another listener on same LB", "fix": {"strategy": "retry", "action": "hcloud ELB listListeners --lb_id {{output.lb_id}}; pick unused port"}, "prevention": "Track listener ports in inventory"},
            {"id": "ELB-FP004", "category": "permission", "signature": {"error_code": "ELB.0301", "error_message_regex": "Quota exceeded|LbQuota", "command_pattern": "*"}, "root_cause": "LB / listener / backend quota exhausted", "fix": {"strategy": "halt", "action": "Delegate to huaweicloud-iam-ops for quota raise"}, "prevention": "Check quota via showQuota before bulk LB ops"},
            {"id": "ELB-FP005", "category": "cross_skill", "signature": {"error_code": "ELB.0401", "error_message_regex": "subnet.*not.*found|invalid subnet", "command_pattern": "create-loadbalancer"}, "root_cause": "LB subnet does not exist or in different VPC than backend", "fix": {"strategy": "delegate", "action": "Delegate to huaweicloud-vpc-ops to verify subnet; ensure LB subnet + backend subnet share VPC"}, "prevention": "Validate LB subnet + backend subnet VPC alignment"},
            {"id": "ELB-FP006", "category": "runtime", "signature": {"error_code": "", "error_message_regex": "RequestLimitExceeded|Throttling", "command_pattern": "*"}, "root_cause": "API rate limit on ELB control plane", "fix": {"strategy": "retry", "action": "Exponential backoff with jitter; respect Retry-After"}, "prevention": "Throttle to <10 req/s for ELB API"},
            {"id": "ELB-FP007", "category": "resource_state", "signature": {"error_code": "ELB.0501", "error_message_regex": "certificate.*invalid|cert.*expired", "command_pattern": "*"}, "root_cause": "ELB HTTPS listener cert expired or uploaded wrong format", "fix": {"strategy": "fallback", "action": "Delegate to huaweicloud-kms-ops to upload new cert; update listener: hcloud ELB updateListener --cert_id {{output.new_cert_id}}"}, "prevention": "Alarm cert expiry at 30d via CES"},
            {"id": "ELB-FP008", "category": "resource_state", "signature": {"error_code": "ELB.0601", "error_message_regex": "backend.*weight.*invalid|WeightInvalid", "command_pattern": "update-member"}, "root_cause": "Member weight outside [0, 100]", "fix": {"strategy": "retry", "action": "Clamp weight to 0..100; 0 means drain (no new connections)"}, "prevention": "Validate weight range client-side before submit"},
            {"id": "ELB-FP009", "category": "network", "signature": {"error_code": "ELB.0700", "error_message_regex": "bandwidth.*exceeded|LbBandwidth", "command_pattern": "*"}, "root_cause": "LB bandwidth cap reached", "fix": {"strategy": "fallback", "action": "Upgrade LB spec: hcloud ELB changeLoadbalancerChargeMode --lb_id {{output.lb_id}} --type payg"}, "prevention": "Monitor CES `lb_bandwidth_util`; alarm at 80%"},
            {"id": "ELB-FP010", "category": "resource_state", "signature": {"error_code": "ELB.0801", "error_message_regex": "draining.*timeout|ConnectionDrained", "command_pattern": "*"}, "root_cause": "Backend removal blocked by lingering connections past drain timeout", "fix": {"strategy": "fallback", "action": "Force remove after drain timeout: hcloud ELB batchRemoveMembers --lb_id {{output.lb_id}} --members {{output.member_ids}} --force"}, "prevention": "Tune connection-drain timeout to <300s; reduce stuck connections"},
        ],
        "playbooks": [
            {"id": "ELB-R001", "name": "Unhealthy Backend Replace", "trigger": {"metric": "lb_member_unhealthy", "condition": "1+ backend unhealthy for 3min", "namespace": "SYS.ELB"}, "diagnosis": {"steps": ["hcloud ELB listMembers --lb_id {{output.lb_id}}", "hcloud CES getMetricData --namespace SYS.ELB --metric_name health_check_status --period 60"], "confidence_factors": ["unhealthy_confirmed", "as_group_available", "backup_in_cbr"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.9, "preconditions": ["hcloud ELB showLoadBalancer --lb_id {{output.lb_id}} | grep -q ACTIVE"], "dry_run": "hcloud ELB batchRemoveMembers --lb_id {{output.lb_id}} --members {{output.unhealthy_ids}} --dry-run", "execute": "hcloud ELB batchRemoveMembers --lb_id {{output.lb_id}} --members {{output.unhealthy_ids}}", "verification": "hcloud ELB listMembers --lb_id {{output.lb_id}} | grep -qv {{output.unhealthy_ids}}", "rollback": "hcloud ELB batchAddMembers --lb_id {{output.lb_id}} --members {{output.unhealthy_ids}}", "timeout_seconds": 60}, "escalation": {"condition": "all backends unhealthy or AS group unavailable", "channel": "notification+pagerduty"}, "metadata": {"success_rate": 0.97, "avg_execution_seconds": 30, "last_updated": NOW, "learned_from": []}},
            {"id": "ELB-R002", "name": "Backend Weight Drain", "trigger": {"metric": "lb_member_error_rate", "condition": "> 50% errors for 5min", "namespace": "SYS.ELB"}, "diagnosis": {"steps": ["hcloud CES getMetricData --namespace SYS.ELB --metric_name 4xx_rate --period 60", "hcloud ELB listMembers --lb_id {{output.lb_id}}"], "confidence_factors": ["errors_sustained", "instance_isolated", "no_other_traffic_drop"]}, "remediation": {"risk_level": "low", "auto_execute_threshold": 0.85, "preconditions": ["hcloud ELB listMembers --lb_id {{output.lb_id}} | grep -q {{output.member_id}}"], "dry_run": "hcloud ELB updateMember --lb_id {{output.lb_id}} --member_id {{output.member_id}} --weight 0 --dry-run", "execute": "hcloud ELB updateMember --lb_id {{output.lb_id}} --member_id {{output.member_id}} --weight 0", "verification": "hcloud ELB showMember --lb_id {{output.lb_id}} --member_id {{output.member_id}} | grep -q weight.*0", "rollback": "hcloud ELB updateMember --lb_id {{output.lb_id}} --member_id {{output.member_id}} --weight {{output.old_weight}}", "timeout_seconds": 30}, "escalation": {"condition": "errors persist after drain (multiple members affected)", "channel": "notification"}, "metadata": {"success_rate": 0.98, "avg_execution_seconds": 10, "last_updated": NOW, "learned_from": []}},
            {"id": "ELB-R003", "name": "HTTPS Cert Rotation", "trigger": {"metric": "cert_expires_in_days", "condition": "< 30 days", "namespace": "SYS.ELB"}, "diagnosis": {"steps": ["hcloud KMS listCertificates --status ACTIVE", "hcloud ELB listListeners --lb_id {{output.lb_id}} --protocol HTTPS"], "confidence_factors": ["cert_expiring", "new_cert_uploaded", "old_cert_archived"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.95, "preconditions": ["hcloud KMS showCertificate --cert_id {{output.new_cert_id}} | grep -q ACTIVE"], "dry_run": "hcloud ELB updateListener --lb_id {{output.lb_id}} --listener_id {{output.listener_id}} --cert_id {{output.new_cert_id}} --dry-run", "execute": "hcloud ELB updateListener --lb_id {{output.lb_id}} --listener_id {{output.listener_id}} --cert_id {{output.new_cert_id}}", "verification": "hcloud ELB showListener --lb_id {{output.lb_id}} --listener_id {{output.listener_id}} | grep -q {{output.new_cert_id}}", "rollback": "hcloud ELB updateListener --lb_id {{output.lb_id}} --listener_id {{output.listener_id}} --cert_id {{output.old_cert_id}}", "timeout_seconds": 60}, "escalation": {"condition": "new cert not yet uploaded or rotation causes 5xx spike", "channel": "notification+pagerduty"}, "metadata": {"success_rate": 0.99, "avg_execution_seconds": 30, "last_updated": NOW, "learned_from": []}},
            {"id": "ELB-R004", "name": "Listener Rule Auto-Scale Out", "trigger": {"metric": "lb_active_connections", "condition": "> 80% of capacity", "namespace": "SYS.ELB"}, "diagnosis": {"steps": ["hcloud CES getMetricData --namespace SYS.ELB --metric_name active_connections --period 60", "hcloud AS listScalingGroups --lb_id {{output.lb_id}}"], "confidence_factors": ["connections_saturated", "as_group_healthy", "quota_available"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.85, "preconditions": ["hcloud AS showScalingGroup --scaling_group_id {{output.sg_id}} | grep -q ACTIVE"], "dry_run": "hcloud AS scalingInstances --scaling_group_id {{output.sg_id}} --dry-run", "execute": "hcloud AS executeScalingAction --scaling_group_id {{output.sg_id}} --action_type ADD --instance_number 2", "verification": "hcloud CES getMetricData --namespace SYS.ELB --metric_name active_connections --period 60 | python3 -c \"import sys,json; d=json.load(sys.stdin); sys.exit(0 if d[-1]['average']<70 else 1)\"", "rollback": "hcloud AS removeInstances --scaling_group_id {{output.sg_id}} --instance_ids {{output.new_instance_ids}}", "timeout_seconds": 300}, "escalation": {"condition": "AS group not configured or quota exhausted", "channel": "notification"}, "metadata": {"success_rate": 0.94, "avg_execution_seconds": 180, "last_updated": NOW, "learned_from": []}},
        ],
    },
    "cce": {
        "patterns": [
            {"id": "CCE-FP001", "category": "resource_state", "signature": {"error_code": "CCE.0140", "error_message_regex": "cluster.*not found|ClusterNotFound", "command_pattern": "*"}, "root_cause": "Cluster ID invalid or cluster deleted", "fix": {"strategy": "retry", "action": "hcloud CCE listClusters --region {{env.HW_REGION_ID}}"}, "prevention": "Cache cluster ID at provisioning time"},
            {"id": "CCE-FP002", "category": "resource_state", "signature": {"error_code": "CCE.0150", "error_message_regex": "node.*not.*ready|NodeNotReady", "command_pattern": "*"}, "root_cause": "Worker node unreachable: kubelet down or network partition", "fix": {"strategy": "fallback", "action": "Inspect node: hcloud CCE showNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}}; check kubelet + network"}, "prevention": "Monitor node_ready via CES; alarm at <0.8"},
            {"id": "CCE-FP003", "category": "resource_state", "signature": {"error_code": "CCE.0200", "error_message_regex": "pod.*Pending|PodSchedulingFailed", "command_pattern": "*"}, "root_cause": "Insufficient cluster resources or node selector mismatch", "fix": {"strategy": "fallback", "action": "Describe pod events: hcloud CCE showPod --cluster_id {{output.cluster_id}} --namespace {{output.ns}} --name {{output.pod}}; check node capacity"}, "prevention": "Set HPA + resource requests/limits on all deployments"},
            {"id": "CCE-FP004", "category": "permission", "signature": {"error_code": "CCE.0300", "error_message_regex": "Quota exceeded|ClusterQuota", "command_pattern": "*"}, "root_cause": "Cluster / node / pod quota exhausted", "fix": {"strategy": "halt", "action": "Delegate to huaweicloud-iam-ops for quota raise"}, "prevention": "Check quota via showQuota before bulk node add"},
            {"id": "CCE-FP005", "category": "cross_skill", "signature": {"error_code": "CCE.0400", "error_message_regex": "image.*not found|ImageNotFound", "command_pattern": "*"}, "root_cause": "SWR image tag missing or auth failed", "fix": {"strategy": "delegate", "action": "Delegate to huaweicloud-swr-ops to verify/push image; verify pull secret"}, "prevention": "Pre-pull images to local registry; cache tags"},
            {"id": "CCE-FP006", "category": "runtime", "signature": {"error_code": "", "error_message_regex": "RequestLimitExceeded|Throttling", "command_pattern": "*"}, "root_cause": "API rate limit on CCE control plane", "fix": {"strategy": "retry", "action": "Exponential backoff with jitter"}, "prevention": "Throttle to <5 req/s"},
            {"id": "CCE-FP007", "category": "resource_state", "signature": {"error_code": "CCE.0501", "error_message_regex": "PersistentVolumeClaim.*Pending|PvcPending", "command_pattern": "*"}, "root_cause": "No available PV or storage class misconfigured", "fix": {"strategy": "fallback", "action": "hcloud CCE listPvcs --cluster_id {{output.cluster_id}}; check storage class + CSI driver"}, "prevention": "Validate storage class in deployment manifest"},
            {"id": "CCE-FP008", "category": "resource_state", "signature": {"error_code": "CCE.0601", "error_message_regex": "addons.*install.*failed|AddonInstallFailed", "command_pattern": "install-addon"}, "root_cause": "CCE addon installation failed: chart repo unreachable or version mismatch", "fix": {"strategy": "retry", "action": "Retry with explicit version: hcloud CCE installAddon --cluster_id {{output.id}} --addon {{output.name}} --version {{output.v}}"}, "prevention": "Pin addon versions; mirror chart repos"},
            {"id": "CCE-FP009", "category": "network", "signature": {"error_code": "CCE.0700", "error_message_regex": "NetworkPolicy.*conflict|NetworkPolicyInvalid", "command_pattern": "*"}, "root_cause": "Conflicting NetworkPolicy rules blocking pod-to-pod traffic", "fix": {"strategy": "fallback", "action": "List NetworkPolicies: kubectl get networkpolicy -A; dedupe overlapping selectors"}, "prevention": "Adopt deny-by-default + explicit allow model"},
            {"id": "CCE-FP010", "category": "runtime", "signature": {"error_code": "CCE.0800", "error_message_regex": "etcd.*unhealthy|EtcdNotHealthy", "command_pattern": "*"}, "root_cause": "Control plane etcd unhealthy: disk pressure or quorum loss", "fix": {"strategy": "halt", "action": "Escalate to CCE support; do not attempt repair (risk of data loss)"}, "prevention": "Monitor etcd metrics; alarm on leader changes > 5/min"},
        ],
        "playbooks": [
            {"id": "CCE-R001", "name": "NotReady Node Cordon + Drain", "trigger": {"metric": "node_ready", "condition": "== 0 (NotReady) for 3min", "namespace": "SYS.CCE"}, "diagnosis": {"steps": ["hcloud CCE showNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}}", "hcloud CES getMetricData --namespace SYS.CCE --metric_name node_ready --period 60"], "confidence_factors": ["node_notready_confirmed", "as_group_available", "no_etcd_pressure"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.9, "preconditions": ["hcloud CCE showNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}} | grep -q NotReady"], "dry_run": "hcloud CCE cordonNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}} --dry-run", "execute": "hcloud CCE cordonNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}} && hcloud CCE drainNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}} --ignore-daemonsets", "verification": "hcloud CCE listPods --cluster_id {{output.cluster_id}} --node {{output.node_id}} | wc -l | grep -q '^0$'", "rollback": "hcloud CCE uncordonNode --cluster_id {{output.cluster_id}} --node_id {{output.node_id}}", "timeout_seconds": 600}, "escalation": {"condition": "drain fails or pods cannot reschedule (PDB violation)", "channel": "notification+pagerduty"}, "metadata": {"success_rate": 0.95, "avg_execution_seconds": 300, "last_updated": NOW, "learned_from": []}},
            {"id": "CCE-R002", "name": "Pending Pod Auto-Scale", "trigger": {"metric": "pending_pods", "condition": "> 5 pending for 5min", "namespace": "SYS.CCE"}, "diagnosis": {"steps": ["hcloud CCE listPods --cluster_id {{output.cluster_id}} --phase Pending", "hcloud CCE showNode --cluster_id {{output.cluster_id}} --limit 50"], "confidence_factors": ["resources_exhausted", "as_group_healthy", "quota_available"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.85, "preconditions": ["hcloud AS showScalingGroup --scaling_group_id {{output.sg_id}} | grep -q ACTIVE"], "dry_run": "hcloud AS scalingInstances --scaling_group_id {{output.sg_id}} --dry-run", "execute": "hcloud AS executeScalingAction --scaling_group_id {{output.sg_id}} --action_type ADD --instance_number 1", "verification": "hcloud CCE listPods --cluster_id {{output.cluster_id}} --phase Pending | wc -l | python3 -c \"import sys; sys.exit(0 if int(sys.stdin.read().strip())<3 else 1)\"", "rollback": "hcloud AS removeInstances --scaling_group_id {{output.sg_id}} --instance_ids {{output.new_node_id}}", "timeout_seconds": 300}, "escalation": {"condition": "AS group unavailable or quota exhausted", "channel": "notification"}, "metadata": {"success_rate": 0.93, "avg_execution_seconds": 180, "last_updated": NOW, "learned_from": []}},
            {"id": "CCE-R003", "name": "Addon Restart", "trigger": {"metric": "addon_health", "condition": "== Abnormal for 5min", "namespace": "SYS.CCE"}, "diagnosis": {"steps": ["hcloud CCE listAddons --cluster_id {{output.cluster_id}}", "hcloud CES getMetricData --namespace SYS.CCE --metric_name addon_status --period 60"], "confidence_factors": ["addon_abnormal", "version_pinned", "no_active_upgrade"]}, "remediation": {"risk_level": "low", "auto_execute_threshold": 0.85, "preconditions": ["hcloud CCE showAddon --cluster_id {{output.cluster_id}} --addon_name {{output.name}} | grep -q Abnormal"], "dry_run": "hcloud CCE restartAddon --cluster_id {{output.cluster_id}} --addon_name {{output.name}} --dry-run", "execute": "hcloud CCE restartAddon --cluster_id {{output.cluster_id}} --addon_name {{output.name}}", "verification": "hcloud CCE showAddon --cluster_id {{output.cluster_id}} --addon_name {{output.name}} | grep -q Running", "rollback": None, "timeout_seconds": 120}, "escalation": {"condition": "restart fails or addon version mismatch", "channel": "notification"}, "metadata": {"success_rate": 0.96, "avg_execution_seconds": 60, "last_updated": NOW, "learned_from": []}},
            {"id": "CCE-R004", "name": "Evicted Pod Workload Restart", "trigger": {"metric": "evicted_pods", "condition": "> 3 in 5min", "namespace": "SYS.CCE"}, "diagnosis": {"steps": ["hcloud CCE listPods --cluster_id {{output.cluster_id}} --phase Failed", "hcloud CCE showEvents --cluster_id {{output.cluster_id}} --reason Evicted --limit 20"], "confidence_factors": ["disk_pressure_confirmed", "node_drainable", "quota_available"]}, "remediation": {"risk_level": "medium", "auto_execute_threshold": 0.9, "preconditions": ["hcloud CCE showNode --cluster_id {{output.cluster_id}} --node_id {{output.evictor_node_id}} | grep -q MemoryPressure\\|DiskPressure"], "dry_run": "hcloud CCE cordonNode --cluster_id {{output.cluster_id}} --node_id {{output.evictor_node_id}} --dry-run", "execute": "hcloud CCE cordonNode --cluster_id {{output.cluster_id}} --node_id {{output.evictor_node_id}} && hcloud CCE drainNode --cluster_id {{output.cluster_id}} --node_id {{output.evictor_node_id}} --ignore-daemonsets --delete-local-data", "verification": "hcloud CCE listPods --cluster_id {{output.cluster_id}} --node {{output.evictor_node_id}} | wc -l | grep -q '^0$'", "rollback": "hcloud CCE uncordonNode --cluster_id {{output.cluster_id}} --node_id {{output.evictor_node_id}}", "timeout_seconds": 600}, "escalation": {"condition": "evictions continue on multiple nodes (cluster-wide pressure)", "channel": "notification+pagerduty"}, "metadata": {"success_rate": 0.92, "avg_execution_seconds": 300, "last_updated": NOW, "learned_from": []}},
        ],
    },
}


def write_patterns(skill_short: str, payload: dict[str, list[dict]]) -> None:
    """Write failure_patterns.json + remediation-playbooks.json for a skill."""
    skill_id = f"huaweicloud-{skill_short}-ops"
    target_dir = ROOT / f"huaweicloud-{skill_short}-ops" / "assets"

    fp_payload = {
        "$schema": "failure-patterns/v1",
        "skill_id": skill_id,
        "patterns": payload["patterns"],
        "meta": {
            "total_patterns": len(payload["patterns"]),
            "last_aggregation": NOW,
            "source_traces_analyzed": 0,
        },
    }
    rp_payload = {
        "$schema": "remediation-playbooks/v1",
        "skill_id": skill_id,
        "playbooks": payload["playbooks"],
    }

    fp_path = target_dir / "failure_patterns.json"
    rp_path = target_dir / "remediation-playbooks.json"

    fp_path.write_text(json.dumps(fp_payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    rp_path.write_text(json.dumps(rp_payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  {skill_id}: {len(payload['patterns'])} patterns + {len(payload['playbooks'])} playbooks")


def main() -> int:
    for short, payload in PRODUCTS.items():
        write_patterns(short, payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())